import { Place } from './types.js';

const places: Array<Place> = [
  {
    name: 'Jaunciema pamatskola',
    address: 'JAUNCIEMA 4. ŠĶĒRSLĪNIJA 4, ZIEMEĻU RAJONS, RĪGA, LV-1023',
    language: 'Latviešu',
    age: 1.5,
    applications: 54,
  },
  {
    name: 'Rīgas 106. pirmsskolas izglītības iestāde',
    address: 'ŪNIJAS IELA 83, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1084',
    language: 'Latviešu',
    age: 1.5,
    applications: 526,
  },
  {
    name: 'Rīgas 11. pirmsskolas izglītības iestāde',
    address: 'RAŅĶA DAMBIS 3, KURZEMES RAJONS, RĪGA, LV-1048',
    language: 'Latviešu',
    age: 1.5,
    applications: 145,
  },
  {
    name: 'Rīgas 123. pirmsskolas izglītības iestāde',
    address: 'KRISTAPA IELA 39, KURZEMES RAJONS, RĪGA, LV-1046',
    language: 'Latviešu',
    age: 1.5,
    applications: 352,
  },
  {
    name: 'Rīgas 124. pirmsskolas izglītības iestāde "Dzērvenīte"',
    address: 'BĒRZUPES IELA 3, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1004',
    language: 'Latviešu',
    age: 1.5,
    applications: 225,
  },
  {
    name: 'Rīgas 135. pirmsskolas izglītības iestāde "Liepziediņi"',
    address: 'ČIEKURKALNA 1. LĪNIJA 53a, ZIEMEĻU RAJONS, RĪGA, LV-1026',
    language: 'Latviešu',
    age: 1.5,
    applications: 358,
  },
  {
    name: 'Rīgas 13. pirmsskolas izglītības iestāde "Ābecītis"',
    address: 'ALTONAVAS IELA 1, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1004',
    language: 'Latviešu',
    age: 1.5,
    applications: 574,
  },
  {
    name: 'Rīgas 14. pirmsskolas izglītības iestāde',
    address: 'VIRCAVAS IELA 2, KURZEMES RAJONS, RĪGA, LV-1083',
    language: 'Latviešu',
    age: 1.5,
    applications: 54,
  },
  {
    name: 'Rīgas 154. pirmsskolas izglītības iestāde',
    address: 'ANDROMEDAS GATVE 3, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1084',
    language: 'Latviešu',
    age: 1.5,
    applications: 201,
  },
  {
    name: 'Rīgas 160. pirmsskolas izglītības iestāde',
    address: 'VANGAŽU IELA 40a, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1024',
    language: 'Latviešu',
    age: 1.5,
    applications: 421,
  },
  {
    name: 'Rīgas 161. pirmsskolas izglītības iestāde',
    address: 'AUGUSTA DOMBROVSKA IELA 9c, ZIEMEĻU RAJONS, RĪGA, LV-1015',
    language: 'Latviešu',
    age: 1.5,
    applications: 14,
  },
  {
    name: 'Rīgas 167. pirmsskolas izglītības iestāde',
    address: 'RAUNAS IELA 43b, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1084',
    language: 'Latviešu',
    age: 1.5,
    applications: 589,
  },
  {
    name: 'Rīgas 169. pirmsskolas izglītības iestāde',
    address: 'VIESTURA PROSPEKTS 27, ZIEMEĻU RAJONS, RĪGA, LV-1005',
    language: 'Latviešu',
    age: 1.5,
    applications: 168,
  },
  {
    name: 'Rīgas 170. pirmsskolas izglītības iestāde',
    address:
      'FIRSA SADOVŅIKOVA IELA 20A, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1003',
    language: 'Latviešu',
    age: 1.5,
    applications: 223,
  },
  {
    name: 'Rīgas 173. pirmsskolas izglītības iestāde',
    address: 'MASKAVAS IELA 254, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1063',
    language: 'Latviešu',
    age: 1.5,
    applications: 267,
  },
  {
    name: 'Rīgas 182. pirmsskolas izglītības iestāde',
    address: 'DZELZAVAS IELA 17a, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1084',
    language: 'Latviešu',
    age: 1.5,
    applications: 546,
  },
  {
    name: 'Rīgas 192. pirmsskolas izglītības iestāde',
    address: 'KĀRĻA VATSONA IELA 11A, ZIEMEĻU RAJONS, RĪGA, LV-1014',
    language: 'Latviešu',
    age: 1.5,
    applications: 83,
  },
  {
    name: 'Rīgas 197. pirmsskolas izglītības iestāde',
    address: 'BIRZES IELA 44, KURZEMES RAJONS, RĪGA, LV-1016',
    language: 'Latviešu',
    age: 1.5,
    applications: 40,
  },
  {
    name: 'Rīgas 200. pirmsskolas izglītības iestāde',
    address: 'AKAS IELA 1, CENTRA RAJONS, RĪGA, LV-1011',
    language: 'Latviešu',
    age: 1.5,
    applications: 943,
  },
  {
    name: 'Rīgas 208. pirmsskolas izglītības iestāde',
    address: 'SALASPILS IELA 18 k-5, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1057',
    language: 'Latviešu',
    age: 1.5,
    applications: 254,
  },
  {
    name: 'Rīgas 209. pirmsskolas izglītības iestāde "Bitīte"',
    address: 'BIŠU IELA 5, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1002',
    language: 'Latviešu',
    age: 1.5,
    applications: 341,
  },
  {
    name: 'Rīgas 213. pirmsskolas izglītības iestāde',
    address: 'VESETAS IELA 11, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1013',
    language: 'Latviešu',
    age: 1.5,
    applications: 872,
  },
  {
    name: 'Rīgas 215. pirmsskolas izglītības iestāde',
    address: 'USMAS IELA 10, KURZEMES RAJONS, RĪGA, LV-1083',
    language: 'Latviešu',
    age: 1.5,
    applications: 185,
  },
  {
    name: 'Rīgas 216. pirmsskolas izglītības iestāde',
    address: 'SALASPILS IELA 10, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1057',
    language: 'Latviešu',
    age: 1.5,
    applications: 174,
  },
  {
    name: 'Rīgas 21. pirmsskolas izglītības iestāde "Laimiņa"',
    address: 'KALNGALES IELA 2, ZIEMEĻU RAJONS, RĪGA, LV-1015',
    language: 'Latviešu',
    age: 1.5,
    applications: 100,
  },
  {
    name: 'Rīgas 220. pirmsskolas izglītības iestāde',
    address: 'IZVALTAS IELA 2, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1057',
    language: 'Latviešu',
    age: 1.5,
    applications: 216,
  },
  {
    name: 'Rīgas 221. pirmsskolas izglītības iestāde',
    address: 'KAZARMU IELA 1a, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1013',
    language: 'Latviešu',
    age: 1.5,
    applications: 418,
  },
  {
    name: 'Rīgas 224. pirmsskolas izglītības iestāde',
    address: 'PRŪŠU IELA 82, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1057',
    language: 'Latviešu',
    age: 1.5,
    applications: 206,
  },
  {
    name: 'Rīgas 225. pirmsskolas izglītības iestāde',
    address: 'IKŠĶILES IELA 10, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1057',
    language: 'Latviešu',
    age: 1.5,
    applications: 152,
  },
  {
    name: 'Rīgas 229. pirmsskolas izglītības iestāde',
    address: 'OGRES IELA 8, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1019',
    language: 'Latviešu',
    age: 1.5,
    applications: 184,
  },
  {
    name: 'Rīgas 232. pirmsskolas izglītības iestāde',
    address: 'AUGUSTA DOMBROVSKA IELA 87, ZIEMEĻU RAJONS, RĪGA, LV-1015',
    language: 'Latviešu',
    age: 1.5,
    applications: 15,
  },
  {
    name: 'Rīgas 233. pirmsskolas izglītības iestāde',
    address: 'MADONAS IELA 24B, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1084',
    language: 'Latviešu',
    age: 1.5,
    applications: 210,
  },
  {
    name: 'Rīgas 234. pirmsskolas izglītības iestāde',
    address: 'KURZEMES PROSPEKTS 86C, KURZEMES RAJONS, RĪGA, LV-1069',
    language: 'Latviešu',
    age: 1.5,
    applications: 123,
  },
  {
    name: 'Rīgas 241. pirmsskolas izglītības iestāde',
    address: 'HIPOKRĀTA IELA 25, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1079',
    language: 'Latviešu',
    age: 1.5,
    applications: 300,
  },
  {
    name: 'Rīgas 244. pirmsskolas izglītības iestāde',
    address: 'MARSA GATVE 8, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1082',
    language: 'Latviešu',
    age: 1.5,
    applications: 192,
  },
  {
    name: 'Rīgas 251. pirmsskolas izglītības iestāde "Mežciems"',
    address: 'MEŽCIEMA IELA 43A, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1079',
    language: 'Latviešu',
    age: 1.5,
    applications: 414,
  },
  {
    name: 'Rīgas 255. pirmsskolas izglītības iestāde',
    address:
      'AKADĒMIĶA MSTISLAVA KELDIŠA IELA 5, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1082',
    language: 'Latviešu',
    age: 1.5,
    applications: 257,
  },
  {
    name: 'Rīgas 256. pirmsskolas izglītības iestāde',
    address: 'ILŪKSTES IELA 28, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1082',
    language: 'Latviešu',
    age: 1.5,
    applications: 142,
  },
  {
    name: 'Rīgas 258. pirmsskolas izglītības iestāde',
    address: 'TĪNŪŽU IELA 1, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1021',
    language: 'Latviešu',
    age: 1.5,
    applications: 101,
  },
  {
    name: 'Rīgas 262. pirmsskolas izglītības iestāde',
    address: 'JUKUMA VĀCIEŠA IELA 2E, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1021',
    language: 'Latviešu',
    age: 1.5,
    applications: 130,
  },
  {
    name: 'Rīgas 266. pirmsskolas izglītības iestāde',
    address: 'PĻAVNIEKU IELA 4, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1021',
    language: 'Latviešu',
    age: 1.5,
    applications: 218,
  },
  {
    name: 'Rīgas 267. pirmsskolas izglītības iestāde',
    address: 'DRAVNIEKU IELA 8, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1021',
    language: 'Latviešu',
    age: 1.5,
    applications: 86,
  },
  {
    name: 'Rīgas 270. pirmsskolas izglītības iestāde',
    address: 'SALNAS IELA 18, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1021',
    language: 'Latviešu',
    age: 1.5,
    applications: 158,
  },
  {
    name: 'Rīgas 272. pirmsskolas izglītības iestāde "Pērlīte"',
    address: 'JELGAVAS IELA 86A, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1004',
    language: 'Latviešu',
    age: 1.5,
    applications: 201,
  },
  {
    name: 'Rīgas 275. pirmsskolas izglītības iestāde "Austriņa"',
    address: 'DIŽOZOLU IELA 6, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1058',
    language: 'Latviešu',
    age: 1.5,
    applications: 640,
  },
  {
    name: 'Rīgas 27. pirmsskolas izglītības iestāde',
    address: 'STENDES IELA 4, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1046',
    language: 'Latviešu',
    age: 1.5,
    applications: 190,
  },
  {
    name: 'Rīgas 36. pirmsskolas izglītības iestāde',
    address: 'LUGAŽU IELA 8, ZIEMEĻU RAJONS, RĪGA, LV-1045',
    language: 'Latviešu',
    age: 1.5,
    applications: 63,
  },
  {
    name: 'Rīgas 41. pirmsskolas izglītības iestāde',
    address: 'LUDZAS IELA 74, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1003',
    language: 'Latviešu',
    age: 1.5,
    applications: 78,
  },
  {
    name: 'Rīgas 42. pirmsskolas izglītības iestāde',
    address: 'SOFIJAS IELA 3, ZIEMEĻU RAJONS, RĪGA, LV-1005',
    language: 'Latviešu',
    age: 1.5,
    applications: 38,
  },
  {
    name: 'Rīgas 46. pirmsskolas izglītības iestāde',
    address: 'VECUMNIEKU IELA 5a, KURZEMES RAJONS, RĪGA, LV-1067',
    language: 'Latviešu',
    age: 1.5,
    applications: 126,
  },
  {
    name: 'Rīgas 49. pirmsskolas izglītības iestāde',
    address: 'GROSTONAS IELA 6, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1013',
    language: 'Latviešu',
    age: 1.5,
    applications: 656,
  },
  {
    name: 'Rīgas 4. pirmsskolas izglītības iestāde "Avotiņš"',
    address: 'ĪSLĪCES IELA 10, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1058',
    language: 'Latviešu',
    age: 1.5,
    applications: 256,
  },
  {
    name: 'Rīgas 57. pirmsskolas izglītības iestāde',
    address: 'MAZĀ CAUNES IELA 3, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1006',
    language: 'Latviešu',
    age: 1.5,
    applications: 189,
  },
  {
    name: 'Rīgas 5. pirmsskolas izglītības iestāde "Čiekuriņš"',
    address: 'GAUJAS IELA 32b, ZIEMEĻU RAJONS, RĪGA, LV-1026',
    language: 'Latviešu',
    age: 1.5,
    applications: 276,
  },
  {
    name: 'Rīgas 61. pirmsskolas izglītības iestāde',
    address: 'VAIDAVAS IELA 11, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1084',
    language: 'Latviešu',
    age: 1.5,
    applications: 325,
  },
  {
    name: 'Rīgas 62. pirmsskolas izglītības iestāde',
    address: 'ALĪSES IELA 19, KURZEMES RAJONS, RĪGA, LV-1046',
    language: 'Latviešu',
    age: 1.5,
    applications: 152,
  },
  {
    name: 'Rīgas 80. pirmsskolas izglītības iestāde',
    address: 'GARĀ IELA 24, KURZEMES RAJONS, RĪGA, LV-1055',
    language: 'Latviešu',
    age: 1.5,
    applications: 71,
  },
  {
    name: 'Rīgas 80. vidusskola',
    address: 'ANDROMEDAS GATVE 11, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1084',
    language: 'Latviešu',
    age: 1.5,
    applications: 90,
  },
  {
    name: 'Rīgas 81. pirmsskolas izglītības iestāde',
    address: 'GRĪVAS IELA 15, KURZEMES RAJONS, RĪGA, LV-1055',
    language: 'Latviešu',
    age: 1.5,
    applications: 34,
  },
  {
    name: 'Rīgas 85. pamatskola',
    address: 'PURVCIEMA IELA 23A, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1035',
    language: 'Latviešu',
    age: 1.5,
    applications: 135,
  },
  {
    name: 'Rīgas 94. pirmsskolas izglītības iestāde',
    address: 'KRIŠJĀŅA BARONA IELA 97b, CENTRA RAJONS, RĪGA, LV-1012',
    language: 'Latviešu',
    age: 1.5,
    applications: 601,
  },
  {
    name: 'Rīgas 97. pirmsskolas izglītības iestāde',
    address: 'IKŠĶILES IELA 8, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1057',
    language: 'Latviešu',
    age: 1.5,
    applications: 118,
  },
  {
    name: 'Rīgas Juglas vidusskola',
    address: 'KVĒLES IELA 64, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1064',
    language: 'Latviešu',
    age: 1.5,
    applications: 464,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Ābelīte"',
    address: 'KATRĪNAS IELA 5A, ZIEMEĻU RAJONS, RĪGA, LV-1045',
    language: 'Latviešu',
    age: 1.5,
    applications: 234,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Annele"',
    address: 'ANNIŅMUIŽAS BULVĀRIS 78, KURZEMES RAJONS, RĪGA, LV-1069',
    language: 'Latviešu',
    age: 1.5,
    applications: 260,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Asniņš"',
    address: 'MASKAVAS IELA 268C, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1063',
    language: 'Latviešu',
    age: 1.5,
    applications: 144,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Bizmārītes"',
    address: 'MOTORU IELA 8, KURZEMES RAJONS, RĪGA, LV-1055',
    language: 'Latviešu',
    age: 1.5,
    applications: 72,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Blāzmiņa"',
    address: 'SKUJU IELA 14, ZIEMEĻU RAJONS, RĪGA, LV-1015',
    language: 'Latviešu',
    age: 1.5,
    applications: 166,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Cielaviņa"',
    address: 'DAMMES IELA 42, KURZEMES RAJONS, RĪGA, LV-1069',
    language: 'Latviešu',
    age: 1.5,
    applications: 122,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Domino"',
    address: 'ILŪKSTES IELA 2, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1082',
    language: 'Latviešu',
    age: 1.5,
    applications: 105,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Dzilniņa"',
    address: 'DZILNAS IELA 20, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1021',
    language: 'Latviešu',
    age: 1.5,
    applications: 190,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Dzīpariņš"',
    address: 'RŪPNIECĪBAS IELA 21, ZIEMEĻU RAJONS, RĪGA, LV-1045',
    language: 'Latviešu',
    age: 1.5,
    applications: 369,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Jumis"',
    address: 'JAUNROZES IELA 12, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1035',
    language: 'Latviešu',
    age: 1.5,
    applications: 111,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Kadiķītis"',
    address: 'GARĀ IELA 31, KURZEMES RAJONS, RĪGA, LV-1055',
    language: 'Latviešu',
    age: 1.5,
    applications: 161,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Kamenīte"',
    address: 'SLOKAS IELA 126a, KURZEMES RAJONS, RĪGA, LV-1067',
    language: 'Latviešu',
    age: 1.5,
    applications: 133,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Kamolītis"',
    address: 'IĻĢUCIEMA IELA 4, KURZEMES RAJONS, RĪGA, LV-1055',
    language: 'Latviešu',
    age: 1.5,
    applications: 131,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Kurzeme"',
    address: 'SLOKAS IELA 130, KURZEMES RAJONS, RĪGA, LV-1067',
    language: 'Latviešu',
    age: 1.5,
    applications: 88,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Laismiņa"',
    address: 'SLOKAS IELA 211, KURZEMES RAJONS, RĪGA, LV-1069',
    language: 'Latviešu',
    age: 1.5,
    applications: 156,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Liepiņa"',
    address: 'VIESTURA PROSPEKTS 29, ZIEMEĻU RAJONS, RĪGA, LV-1005',
    language: 'Latviešu',
    age: 1.5,
    applications: 88,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Ligzdiņa"',
    address: 'APUZES IELA 74, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1029',
    language: 'Latviešu',
    age: 1.5,
    applications: 158,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Māra"',
    address: 'SESKU IELA 33B, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1082',
    language: 'Latviešu',
    age: 1.5,
    applications: 227,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Mārdega"',
    address: 'TALLINAS IELA 64, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1009',
    language: 'Latviešu',
    age: 1.5,
    applications: 269,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Margrietiņa"',
    address: 'SLOKAS IELA 126, KURZEMES RAJONS, RĪGA, LV-1067',
    language: 'Latviešu',
    age: 1.5,
    applications: 76,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Mežaparks"',
    address: 'STOKHOLMAS IELA 3a, ZIEMEĻU RAJONS, RĪGA, LV-1014',
    language: 'Latviešu',
    age: 1.5,
    applications: 251,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Mežrozīte"',
    address: 'RODODENDRU IELA 6, KURZEMES RAJONS, RĪGA, LV-1083',
    language: 'Latviešu',
    age: 1.5,
    applications: 94,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Ozoliņš"',
    address: 'SLĀVU IELA 19, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1073',
    language: 'Latviešu',
    age: 1.5,
    applications: 119,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Pasaciņa"',
    address: 'EIŽENIJAS IELA 8, KURZEMES RAJONS, RĪGA, LV-1007',
    language: 'Latviešu',
    age: 1.5,
    applications: 81,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Pienenītes"',
    address: 'MORES IELA 8, ZIEMEĻU RAJONS, RĪGA, LV-1034',
    language: 'Latviešu',
    age: 1.5,
    applications: 93,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Pīlādzītis"',
    address: 'AUGŠIELA 8, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1009',
    language: 'Latviešu',
    age: 1.5,
    applications: 125,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Priedīte"',
    address: 'VALENTĪNA IELA 10a, KURZEMES RAJONS, RĪGA, LV-1046',
    language: 'Latviešu',
    age: 1.5,
    applications: 212,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Pūcīte"',
    address: 'ĒRGĻU IELA 1, CENTRA RAJONS, RĪGA, LV-1012',
    language: 'Latviešu',
    age: 1.5,
    applications: 568,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Riekstiņš"',
    address: 'RIEKSTU IELA 14, KURZEMES RAJONS, RĪGA, LV-1055',
    language: 'Latviešu',
    age: 1.5,
    applications: 67,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Rotaļa"',
    address: 'LAUKU IELA 2b, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1009',
    language: 'Latviešu',
    age: 1.5,
    applications: 225,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Rūķītis"',
    address: 'VECMĪLGRĀVJA 1. LĪNIJA 41, ZIEMEĻU RAJONS, RĪGA, LV-1015',
    language: 'Latviešu',
    age: 1.5,
    applications: 114,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Saulstariņi"',
    address: 'GOBAS IELA 27, KURZEMES RAJONS, RĪGA, LV-1016',
    language: 'Latviešu',
    age: 1.5,
    applications: 72,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Sprīdītis"',
    address: 'PĀRSLAS IELA 16, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1002',
    language: 'Latviešu',
    age: 1.5,
    applications: 385,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Vadakstīte"',
    address: 'VADAKSTES IELA 16, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1058',
    language: 'Latviešu',
    age: 1.5,
    applications: 258,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Zilbīte"',
    address: 'MALNAVAS IELA 4, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1057',
    language: 'Latviešu',
    age: 1.5,
    applications: 28,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Zīļuks"',
    address: 'HIPOKRĀTA IELA 25a, VIDZEMES PRIEKŠPILSĒTA, RĪGA, LV-1079',
    language: 'Latviešu',
    age: 1.5,
    applications: 494,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Zvaigznīte"',
    address: 'ZVAIGŽŅU IELA 6, LATGALES PRIEKŠPILSĒTA, RĪGA, LV-1009',
    language: 'Latviešu',
    age: 1.5,
    applications: 318,
  },
  {
    name: 'Rīgas pirmsskolas izglītības iestāde "Zvaniņš"',
    address: 'IMANTAS 18. LĪNIJA 5A, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1029',
    language: 'Latviešu',
    age: 1.5,
    applications: 180,
  },
  {
    name: 'Rīgas Valdorfskola',
    address: 'BALTĀ IELA 10, KURZEMES RAJONS, RĪGA, LV-1055',
    language: 'Latviešu',
    age: 1.5,
    applications: 111,
  },
  {
    name: 'Rīgas Ziepniekkalna pirmsskola',
    address: 'SVĒTES IELA 7, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1058',
    language: 'Latviešu',
    age: 1.5,
    applications: 364,
  },
  {
    name: 'Rīgas Zolitūdes pirmsskola',
    address: 'IMANTAS 18. LĪNIJA 3A, ZEMGALES PRIEKŠPILSĒTA, RĪGA, LV-1029',
    language: 'Latviešu',
    age: 1.5,
    applications: 166,
  },
];

export { places };
